name: Download Builds
description: Downloading the github artifact created with the build (dist folder)
runs:
  using: composite
  steps:
    - name: Download dist folder
      uses: actions/download-artifact@v2
      with:
        name: library-dist-${{ github.sha }}
        path: dist
