name: experiment
on:
  push:
    branches-ignore:
      - 'master'
    pull_request:
      branches:
        - '**'
jobs:
  calculate-test:
    runs-on:
      ubuntu-latest
      # Map a step output to a job output
    outputs:
      e2e-files: ${{ steps.get-test-e2e-files.outputs.files }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: get-test-e2e-files
        name: Obtain test e2e paths
        shell: bash
        run: |
          echo "::set-output name=files::$(node .github/scripts/get-e2e-test-files.js)"

  experiment:
    needs: calculate-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [12, 14, 16]
        node-version: [14]
        # experiment: ${{fromJson(needs.calculate-test.outputs.e2e-files)}}
        experiment: ['build.spec.ts']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      # - run: echo "${{ matrix.node-version }} - ${{ matrix.experiment }}"
      - run: yarn --version
      - run: npx jest ${{ matrix.experiment }} -c e2e/ngx-deploy-npm-e2e/jest.config.js
